/**
 * Notification categories matching business events.
 * Each category corresponds to a specific system event that generates a notification.
 */
export const NOTIFICATION_CATEGORIES = [
  'duplicate_detected',
  'low_confidence',
  'processing_error',
  'sync_conflict',
  'schema_suggestion',
  'export_completed',
  'info',
] as const;

export type NotificationCategory = (typeof NOTIFICATION_CATEGORIES)[number];

/**
 * Related entity types for navigation — which entity the notification links to.
 */
export type NotificationEntityType = 'invoice' | 'batch' | 'schema' | 'product' | 'export';

/**
 * Full props for a Notification (used for reconstitution from DB).
 */
export interface NotificationProps {
  id: string;
  category: NotificationCategory;
  title: string;
  message: string;
  relatedEntityType: NotificationEntityType | null;
  relatedEntityId: string | null;
  isRead: boolean;
  createdAt: Date;
}

/**
 * Props for creating a new Notification.
 */
export interface CreateNotificationProps {
  id?: string;
  category: NotificationCategory;
  title: string;
  message: string;
  relatedEntityType?: NotificationEntityType | null;
  relatedEntityId?: string | null;
}

/**
 * Plain serializable representation of a Notification.
 */
export interface NotificationPlainObject {
  id: string;
  category: NotificationCategory;
  title: string;
  message: string;
  relatedEntityType: NotificationEntityType | null;
  relatedEntityId: string | null;
  isRead: boolean;
  createdAt: string;
}

/**
 * Generate a simple unique ID (matches existing project pattern).
 * @returns A UUID-like string
 */
function generateId(): string {
  return `ntf-${Date.now()}-${Math.random().toString(36).substring(2, 9)}`;
}

/**
 * Notification domain entity.
 *
 * Represents an in-app notification generated by system events
 * (duplicate detection, low confidence, processing errors, sync conflicts, etc.).
 *
 * Notifications are created unread and can be marked as read by the user.
 * Each notification optionally links to a related entity for navigation.
 */
export class Notification {
  private constructor(private readonly props: NotificationProps) {}

  /**
   * Create a new Notification with validation.
   * @param props - Creation properties
   * @returns A new Notification instance
   * @throws Error if title, message, or category is invalid
   */
  static create(props: CreateNotificationProps): Notification {
    const trimmedTitle = props.title.trim();
    if (!trimmedTitle) {
      throw new Error('Title is required');
    }

    const trimmedMessage = props.message.trim();
    if (!trimmedMessage) {
      throw new Error('Message is required');
    }

    if (!NOTIFICATION_CATEGORIES.includes(props.category)) {
      throw new Error(`Invalid notification category: ${props.category}`);
    }

    return new Notification({
      id: props.id ?? generateId(),
      category: props.category,
      title: trimmedTitle,
      message: trimmedMessage,
      relatedEntityType: props.relatedEntityType ?? null,
      relatedEntityId: props.relatedEntityId ?? null,
      isRead: false,
      createdAt: new Date(),
    });
  }

  /**
   * Reconstitute a Notification from stored data (skip validation).
   * @param props - Full notification properties from DB
   * @returns A reconstituted Notification instance
   */
  static reconstitute(props: NotificationProps): Notification {
    return new Notification(props);
  }

  /** @returns The notification's unique identifier */
  get id(): string {
    return this.props.id;
  }

  /** @returns The notification category */
  get category(): NotificationCategory {
    return this.props.category;
  }

  /** @returns The notification title */
  get title(): string {
    return this.props.title;
  }

  /** @returns The notification message */
  get message(): string {
    return this.props.message;
  }

  /** @returns The type of related entity, or null */
  get relatedEntityType(): NotificationEntityType | null {
    return this.props.relatedEntityType;
  }

  /** @returns The ID of the related entity, or null */
  get relatedEntityId(): string | null {
    return this.props.relatedEntityId;
  }

  /** @returns Whether the notification has been read */
  get isRead(): boolean {
    return this.props.isRead;
  }

  /** @returns When the notification was created */
  get createdAt(): Date {
    return this.props.createdAt;
  }

  /**
   * Mark this notification as read. No-op if already read.
   */
  markAsRead(): void {
    (this.props as { isRead: boolean }).isRead = true;
  }

  /**
   * Convert to a plain serializable object (for API responses).
   * @returns Plain object representation
   */
  toPlainObject(): NotificationPlainObject {
    return {
      id: this.props.id,
      category: this.props.category,
      title: this.props.title,
      message: this.props.message,
      relatedEntityType: this.props.relatedEntityType,
      relatedEntityId: this.props.relatedEntityId,
      isRead: this.props.isRead,
      createdAt: this.props.createdAt.toISOString(),
    };
  }
}
